import { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      // TIER 1 – GLOBAL SEARCH ENGINES
      {
        userAgent: [
          "Googlebot",
          "Google-InspectionTool",
          "Googlebot-Image",
          "Googlebot-News",
          "Googlebot-Video",
          "bingbot",
          "msnbot",
          "msnbot-media",
        ],
        disallow: ["/admin/", "/api/", "/temp/", "/private/"],
        allow: "/",
      },
      // TIER 2 – REGIONAL & ALTERNATIVE SEARCH ENGINES
      {
        userAgent: [
          "Baiduspider",
          "SogouBot",
          "YiyanBot",
          "YandexBot",
          "Yeti",
          "naver",
          "Slurp",
          "yahoo",
          "SeznamBot",
          "CocCocBot",
        ],
        disallow: ["/admin/", "/api/", "/private/"],
        allow: "/",
      },
      // TIER 3 – PRIVACY-FIRST & INDEPENDENT SEARCH ENGINES
      {
        userAgent: [
          "Bravebot",
          "duckduckbot",
          "duckassistbot",
          "MojeekBot",
          "MarginaliaBot",
          "WibyBot",
          "wiby",
          "StractBot",
          "AlexandriaBot",
          "Alexandria",
          "QwantBot",
          "StartpageBot",
          "YepBot",
          "EcosiaBot",
          "SwisscowsBot",
          "GibiruBot",
          "PresearchBot",
          "MillionshortBot",
          "DogpileBot",
          "LycosBot",
          "AskBot",
          "YaCyBot",
          "ShodanBot",
          "WolframAlphaBot",
          "SemanticScholarBot",
        ],
        disallow: ["/admin/", "/private/"],
        allow: "/",
      },
      // TIER 4 – AI SEARCH INDEXERS & CITATION RETRIEVERS
      {
        userAgent: [
          "OAI-SearchBot",
          "Claude-SearchBot",
          "PerplexityBot",
          "xAI-Grok",
          "Grok",
          "Grok-DeepSearch",
          "Kimi-SearchBot",
          "AzureAI-SearchBot",
          "MistralAI-SearchBot",
        ],
        disallow: ["/admin/", "/private/"],
        allow: "/",
      },
      // TIER 5 – USER-TRIGGERED RUNTIME FETCHERS
      {
        userAgent: [
          "ChatGPT-User",
          "Claude-User",
          "Perplexity-User",
          "Kimi-User",
          "MistralAI-User",
          "Qwen-User",
          "Gemini-User",
          "Grok-User",
        ],
        disallow: ["/admin/", "/private/"],
        allow: "/",
      },
      // TIER 6 – FOUNDATIONAL AI TRAINING HARVESTERS (BLOCKED)
      {
        userAgent: [
          "GPTBot",
          "ClaudeBot",
          "anthropic-ai",
          "claude-web",
          "Google-Extended",
          "Applebot-Extended",
          "Meta-ExternalAgent",
          "Meta-ExternalFetcher",
          "FacebookBot",
          "GrokBot",
          "xAI-Bot",
          "xAI-Web-Crawler",
          "KimiBot",
          "QwenBot",
          "ChatGLM-Spider",
          "cohere-ai",
          "Amazonbot",
          "AI2Bot",
          "Diffbot",
          "CCBot",
          "Bytespider",
          "Doubaobot",
          "TikTokSpider",
          "laion-huggingface-processor",
          "laion-ai",
          "DeepSeekBot",
          "AI-TrainingBot",
        ],
        disallow: "/",
      },
      // AGGRESSIVE SECURITY SCRAPERS (BLOCKED)
      {
        userAgent: [
          "AhrefsBot",
          "SemrushBot",
          "MajesticBot",
          "rogerbot",
          "DotBot",
          "DataForSEO",
          "ZeusBot",
          "Nutch",
          "Abonti",
          "zgrab",
          "Masscan",
        ],
        disallow: "/",
      },
      // GLOBAL WILD-CARD BACKUP
      {
        userAgent: "*",
        disallow: ["/admin/", "/api/", "/temp/", "/private/"],
        allow: "/",
      },
    ],
    sitemap: [
      "https://packfit.alfo.online/sitemap.xml",
      "https://packfit.alfo.online/sitemap-articles.xml",
      "https://packfit.alfo.online/sitemap-products.xml",
    ],
  };
}
